SELECT * FROM moviestreaming.moviedetails;
select count(*) from moviedetails;
USE moviestreaming;

-- English Movies
INSERT INTO moviedetails VALUES ('2345346716', '_Senorita Zindagi Na Milegi Dobara_ Full HD Video Song _ Farhan Akhtar, Hrithik Roshan, Abhay Deol - Copy - Copy (17).mp4', 'Desc17', 'Comedy', 'English', 'English', '7.4', 'Hrithik Roshan, Abhay Deol, Farhan Akhtar', 'Zoya Akhtar', '2011-07-15', 'http://127.0.0.7/protected-route/thumbnails/gg.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346717', 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Drama', 'English', 'English', '9.3', 'Tim Robbins, Morgan Freeman', 'Frank Darabont', '1994-10-14', 'http://127.0.0.7/protected-route/thumbnails/shawshank_redemption.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346718', 'Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'Sci-fi', 'English', 'English', '8.8', 'Leonardo DiCaprio, Joseph Gordon-Levitt', 'Christopher Nolan', '2010-07-16', 'http://127.0.0.7/protected-route/thumbnails/inception.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346719', 'Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 'Romance', 'English', 'English', '7.8', 'Leonardo DiCaprio, Kate Winslet', 'James Cameron', '1997-12-19', 'http://127.0.0.7/protected-route/thumbnails/titanic.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346720', 'The Hangover', 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.', 'Comedy', 'English', 'English', '7.7', 'Zach Galifianakis, Bradley Cooper', 'Todd Phillips', '2009-06-05', 'http://127.0.0.7/protected-route/thumbnails/hangover.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346721', 'Harry Potter and the Sorcerer\'s Stone', 'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.', 'Fantasy', 'English', 'English', '7.6', 'Daniel Radcliffe, Emma Watson', 'Chris Columbus', '2001-11-16', 'http://127.0.0.7/protected-route/thumbnails/harry_potter.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346722', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save his love, the governor\'s daughter, from Jack\'s former pirate allies, who are now undead.', 'Adventure', 'English', 'English', '8.0', 'Johnny Depp, Orlando Bloom', 'Gore Verbinski', '2003-07-09', 'http://127.0.0.7/protected-route/thumbnails/pirates_caribbean.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346723', 'The Social Network', 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.', 'Biography', 'English', 'English', '7.7', 'Jesse Eisenberg, Andrew Garfield', 'David Fincher', '2010-10-01', 'http://127.0.0.7/protected-route/thumbnails/social_network.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346724', 'Planet Earth II', 'David Attenborough presents a documentary series exploring how animals meet the challenges of surviving in the most iconic habitats on earth.', 'Documentary', 'English', 'English', '9.5', 'David Attenborough', 'Various Directors', '2016-11-06', 'http://127.0.0.7/protected-route/thumbnails/planet_earth.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346725', 'The Conjuring', 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.', 'Horror', 'English', 'English', '7.5', 'Vera Farmiga, Patrick Wilson', 'James Wan', '2013-07-19', 'http://127.0.0.7/protected-route/thumbnails/conjuring.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346726', 'Gone Girl', 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.', 'Thriller', 'English', 'English', '8.1', 'Ben Affleck, Rosamund Pike', 'David Fincher', '2014-10-03', 'http://127.0.0.7/protected-route/thumbnails/gone_girl.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346727', 'Sherlock Holmes', 'Detective Sherlock Holmes and his stalwart partner Watson engage in a battle of wits and brawn with a nemesis whose plot is a threat to all of England.', 'Mystery', 'English', 'English', '7.6', 'Robert Downey Jr., Jude Law', 'Guy Ritchie', '2009-12-25', 'http://127.0.0.7/protected-route/thumbnails/sherlock_holmes.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346728', 'Dunkirk', 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.', 'War', 'English', 'English', '7.9', 'Fionn Whitehead, Barry Keoghan', 'Christopher Nolan', '2017-07-21', 'http://127.0.0.7/protected-route/thumbnails/dunkirk.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346729', 'The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'Award-winning', 'English', 'English', '9.2', 'Marlon Brando, Al Pacino', 'Francis Ford Coppola', '1972-03-24', 'http://127.0.0.7/protected-route/thumbnails/godfather.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346751', 'The Dark Knight', 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'Action', 'English', 'English', '9.0', 'Christian Bale, Heath Ledger', 'Christopher Nolan', '2008-07-18', 'http://127.0.0.7/protected-route/thumbnails/dark_knight.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346752', 'Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', 'Sci-fi', 'English', 'English', '8.6', 'Matthew McConaughey, Anne Hathaway', 'Christopher Nolan', '2014-11-07', 'http://127.0.0.7/protected-route/thumbnails/interstellar.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346753', 'Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Crime', 'English', 'English', '8.9', 'John Travolta, Uma Thurman', 'Quentin Tarantino', '1994-10-14', 'http://127.0.0.7/protected-route/thumbnails/pulp_fiction.png', 'NA');

-- Add more English movies here...

-- Hindi Movies
INSERT INTO moviedetails VALUES ('2345346730', 'Dangal', 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.', 'Biography', 'Hindi', 'Hindi', '8.4', 'Aamir Khan, Sakshi Tanwar', 'Nitesh Tiwari', '2016-12-23', 'http://127.0.0.7/protected-route/thumbnails/dangal.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346731', 'Baahubali: The Beginning', 'In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.', 'Action', 'Hindi', 'Hindi', '8.1', 'Prabhas, Rana Daggubati', 'S.S. Rajamouli', '2015-07-10', 'http://127.0.0.7/protected-route/thumbnails/baahubali.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346732', 'Queen', 'A Delhi girl from a traditional family sets out on a solo honeymoon after her marriage gets canceled.', 'Drama', 'Hindi', 'Hindi', '8.2', 'Kangana Ranaut, Rajkummar Rao', 'Vikas Bahl', '2014-03-07', 'http://127.0.0.7/protected-route/thumbnails/queen.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346733', 'PK', 'An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate the impact of religion on its people.', 'Comedy', 'Hindi', 'Hindi', '8.1', 'Aamir Khan, Anushka Sharma', 'Rajkumar Hirani', '2014-12-19', 'http://127.0.0.7/protected-route/thumbnails/pk.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346734', 'Koi... Mil Gaya', 'A developmentally disabled young man tries to continue the work his father did in communicating with extra-terrestrials from outer space, which leads to something miraculous and wonderful.', 'Sci-fi', 'Hindi', 'Hindi', '7.1', 'Hrithik Roshan, Preity Zinta', 'Rakesh Roshan', '2003-08-08', 'http://127.0.0.7/protected-route/thumbnails/koi_mil_gaya.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346735', 'Barfi!', 'Three young people learn that love can neither be defined nor contained by society\'s norms of normal and abnormal.', 'Romance', 'Hindi', 'Hindi', '8.1', 'Ranbir Kapoor, Priyanka Chopra', 'Anurag Basu', '2012-09-14', 'http://127.0.0.7/protected-route/thumbnails/barfi.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346736', '3 Idiots', 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them "idiots".', 'Comedy', 'Hindi', 'Hindi', '8.4', 'Aamir Khan, Madhavan', 'Rajkumar Hirani', '2009-12-25', 'http://127.0.0.7/protected-route/thumbnails/3_idiots.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346737', 'Lagaan: Once Upon a Time in India', 'The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers.', 'Drama', 'Hindi', 'Hindi', '8.1', 'Aamir Khan, Gracy Singh', 'Ashutosh Gowariker', '2001-06-15', 'http://127.0.0.7/protected-route/thumbnails/lagaan.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346738', 'Tumbbad', 'A mythological story about a goddess who created the entire universe. The plot revolves around the consequences when humans build a temple for her first-born.', 'Horror', 'Hindi', 'Hindi', '8.3', 'Sohum Shah, Anita Date', 'Rahi Anil Barve', '2018-10-12', 'http://127.0.0.7/protected-route/thumbnails/tumbbad.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346739', 'Andhadhun', 'A series of mysterious events change the life of a blind pianist, who must now report a crime that he should technically know nothing of.', 'Thriller', 'Hindi', 'Hindi', '8.3', 'Ayushmann Khurrana, Tabu', 'Sriram Raghavan', '2018-10-05', 'http://127.0.0.7/protected-route/thumbnails/andhadhun.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346740', 'Ghajini', 'A short-term memory loss patient sets out on his journey to avenge the death of his beloved girl.', 'Action', 'Hindi', 'Hindi', '7.3', 'Aamir Khan, Asin', 'A.R. Murugadoss', '2008-12-25', 'http://127.0.0.7/protected-route/thumbnails/ghajini.png', 'NA');
-- Add more Hindi movies here...

-- Bengali Movies
INSERT INTO moviedetails VALUES ('2345346741', 'Baishe Srabon', 'Several murders have taken place through out the city of Kolkata. A Serial killer is believed to be responsible. The mods operandi being that the killer always caries out the murder according to verses in Bengali poetry.', 'Thriller', 'Bengali', 'Bengali', '8.0', 'Prosenjit Chatterjee, Parambrata Chattopadhyay', 'Srijit Mukherji', '2011-09-30', 'http://127.0.0.7/protected-route/thumbnails/baishe_srabon.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346742', 'Chokher Bali', 'A young woman is left to her own devices when her sickly husband dies soon after they move to Calcutta. She returns to her parents\' home and soon attracts the attention of a local ne\'er-do-well.', 'Drama', 'Bengali', 'Bengali', '6.9', 'Aishwarya Rai, Prasenjit Chatterjee', 'Rituparno Ghosh', '2003-10-10', 'http://127.0.0.7/protected-route/thumbnails/chokher_bali.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346743', 'Byomkesh Bakshi', 'Byomkesh Bakshi is a Bengali Detective who is called upon for a spine-chilling case with his assistant cum friend Ajit.', 'Mystery', 'Bengali', 'Bengali', '7.3', 'Abir Chatterjee, Saswata Chatterjee', 'Anjan Dutt', '2010-12-13', 'http://127.0.0.7/protected-route/thumbnails/byomkesh_bakshi.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346744', 'Meghe Dhaka Tara', 'A selfless young woman sacrifices her own happiness for her unappreciative family.', 'Biography', 'Bengali', 'Bengali', '7.6', 'Saswata Chatterjee, Abir Chatterjee', 'Kamaleswar Mukherjee', '2013-08-14', 'http://127.0.0.7/protected-route/thumbnails/meghe_dhaka_tara.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346745', 'Chander Pahar', 'Based on the novel by Bibhutibhushan Bandyopadhyay, the film revolves around a young man named Shankar who adventures into the wilderness of Africa in search of a diamond mine.', 'Adventure', 'Bengali', 'Bengali', '6.8', 'Dev, Gerard Rudolf', 'Kamaleswar Mukherjee', '2013-12-20', 'http://127.0.0.7/protected-route/thumbnails/chander_pahar.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346746', 'Hemlock Society', 'A budding entrepreneur fights social injustice in her application to set up a free school for the marginalized children.', 'Romance', 'Bengali', 'Bengali', '7.2', 'Parambrata Chattopadhyay, Koel Mallick', 'Srijit Mukherji', '2012-06-22', 'http://127.0.0.7/protected-route/thumbnails/hemlock_society.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346747', 'Khaad', 'Neel, a writer by profession, is paid to pen a script for a film. He considers it as an opportunity to get close to the heroine of the film, Rhea, whom he admires. Neel travels to a resort in Balasore, along with the unit of the film and stays there. He finishes writing the script of the film in five days and meets Rhea during this process. But she turns down his advances.', 'Drama', 'Bengali', 'Bengali', '6.7', 'Mithun Chakraborty, Tanusree Chakraborty', 'Kaushik Ganguly', '2014-11-07', 'http://127.0.0.7/protected-route/thumbnails/khaad.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346748', 'Kakababu Here Gelen?', 'Kakababu and Santu will unravel the mystery of the legendary beast, the Yeti in this film.', 'Adventure', 'Bengali', 'Bengali', '6.6', 'Prosenjit Chatterjee, Aryann Bhowmik', 'Srijit Mukherji', '2021-12-31', 'http://127.0.0.7/protected-route/thumbnails/kakababu.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346749', 'Aranyer Din Ratri', 'A group of four friends go for a holiday in a forest and there they meet another group of people and spend their quality time with each other.', 'Comedy', 'Bengali', 'Bengali', '8.2', 'Soumitra Chatterjee, Sharmila Tagore', 'Satyajit Ray', '1970-12-27', 'http://127.0.0.7/protected-route/thumbnails/aranyer_din_ratri.png', 'NA');
INSERT INTO moviedetails VALUES ('2345346750', 'Teen Kanya', 'Teen Kanya is a 1961 Indian Bengali anthology film directed by Satyajit Ray, and based upon short stories by Rabindranath Tagore.', 'Drama', 'Bengali', 'Bengali', '7.9', 'Soumitra Chatterjee, Aparna Sen', 'Satyajit Ray', '1961-02-02', 'http://127.0.0.7/protected-route/thumbnails/teen_kanya.png', 'NA');
-- Add more Bengali movies here...
